# development:
#   host: dev.example.com
#   email: john@doe.net
#   password: apassword
#   # api_key: <your api key here>
# staging:
#   host: staging.example.com
#   email: john@doe.net
#   password: apassword
#   # api_key: <your api key here>
# production:
#   host: www.example.com
#   email: john@doe.net
#   password: apassword
#   # api_key: <your api key here>


local:
  host: 0.0.0.0:3000
  handle: screeching-silence-8251
  email: cedric.lor@gmail.com
  api_key: 07ba764472caae0d4a00abecfe73b124edd2878a
