# Your translations go here. To be used with the 'translate' liquid filter
# Example:
#   {{ 'hello_world' | translate }}
#

# hello_world:
#   en: Hello world !
#   fr: Bonjour le monde !

home_page:
  en: "Home"
  fr: "Accueil"
  ru: "добро пожаловать"
  zh-CN: "家"

read_more:
  en: "Read more..."
  fr: "Lire la suite..."
  ru: "подробнее..."
  zh-CN: "了解更多"

en:
  fr: "English"
  en: "English"
  ru: "English"
  zh-CN: "English"

fr:
  en: "Français"
  fr: "Français"
  ru: "Français"
  zh-CN: "Français"

ru:
  en: "Русский"
  fr: "Русский"
  ru: "Русский"
  zh-CN: "Русский"

zh_CN:
  en: "中文"
  fr: "中文"
  ru: "中文"
  zh-CN: "中文"

languages_for_switcher:
  en: "Languages"
  fr: "Langues"
  ru: "Языки"
  zh-CN: "语言"

site_published_title:
  en: "Centre for the Franco-Russian and Franco-Chinese Friendships"
  fr: "Centre pour l'amitié franco-russe et franco-chinoise"
  ru: "Центр Франко-русский и франко-китайские дружеские"
  zh-CN: "中心法俄和法 - 中国友谊"

posted_at_format:
  en: 'Posted at %-I:%M %p on %B, %-d %Y'
  fr: 'Publié à %-I:%M %p le %-d %B %Y'

locale:
  en: 'English'
  fr: 'Français'
  ru: 'Русский'
  zh_CN: '中文'

the_following_errors_occured:
  en: "The following errors occured"
  fr: "Les erreurs suivantes sont intervenues :"

email_for_form:
  en: 'Email'
  fr: "Email"
  ru: "Эл. адрес"
  zh-CN: "电子邮件"

user_message:
  en: "Message"
  fr: "Message"
  ru: "Сообщение"
  zh-CH: "信息"

submit_btn_txt:
  en: "Submit"
  fr: "Envoyer"
  ru:  "Отправить"
  zh-CN: "提交"

Menu:
  en: "Menu"
  fr: "Menu"
  ru: "меню"
  zh-CN: "导航菜单"

from:
  en: from
  fr: de

to:
  en: to
  fr: to
